import { Footer, Header } from "@/components"
import "./globals.css"
import { Sora } from "next/font/google"

const sora = Sora({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${sora.className} min-h-screen grid grid-rows-[auto_1fr_auto] relative overflow-x-hidden overflow-y-auto`}>
        <Header />
        <main className="bg-zinc-100 sm:bg-zinc-50">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
